---
- name: Create User | Create the final user of deployment
  user:
    name: "{{ deploy_user }}"
    password: "{{ deploy_user_password }}"
    shell: /bin/zsh
    groups: wheel
    append: yes
    state: present
  become: true

- name: Create User | Allow wheel group via sudoers.d without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/01_wheel
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'
  become: yes
