---
- name: Create User| Create the final user of deployment
  user:
    name: "{{ deploy_user }}"
    password: "{{ deploy_user_password }}"
    shell: /bin/zsh
    groups: wheel
    append: yes
    state: present
  become: true

- name: Create User | Allow wheel group in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL: ALL"
    validate: 'visudo -cf %s'
  become: yes
  become_user: root