- name: Obsidian | Create required directories
  file:
    path: "{{ item.opath }}"
    state: directory
  loop:
    - { opath: "/home/{{ deploy_user }}/Documents/Notes" }
    - { opath: "/home/{{ deploy_user }}/.config/obsidian" }
  become: yes
  become_user: "{{ deploy_user }}"

- name: Obsidian | Move obsidian.json to config path
  template:
    src: "obsidian.json.j2"
    dest: "/home/{{ deploy_user }}/.config/obsidian/obsidian.json"
  become: yes
  become_user: "{{ deploy_user }}"

- name: Obsidian | Transfer the configuration files
  copy:
    src: "{{ role_path }}/files/obsidian/"
    dest: "/home/{{ deploy_user }}/Documents/Notes/.obsidian"
  become: yes
  become_user: "{{ deploy_user }}"
