source-file "${HOME}/.tmux/plugins/tmux-themepack/powerline/double/purple.tmuxtheme"
set -g history-limit 10000
set -g default-terminal 'screen-256color'
bind-key -n HOME send Escape "OH"
bind-key -n END send Escape "OF"
